name: ccvc_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.1+80

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart
  dartx: ^0.7.1
  flutter_html: ^2.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  optimized_cached_image: ^3.0.0
  permission_handler: ^9.0.2
  #Favourite library
  share: ^2.0.1
  provider: ^6.0.0
  device_info: 2.0.0
  flutter_bloc: ^7.0.0
  package_info: ^2.0.0
  google_fonts: 2.0.0
  connectivity: ^3.0.3
  url_launcher: 6.0.10
  path_provider: ^2.0.1
  webview_flutter: ^2.0.10
  shared_preferences: ^2.0.5
  lint: ^1.6.0
  table_calendar: ^3.0.2
  image_picker: ^0.8.4+3
  syncfusion_flutter_charts: ^19.4.38
  flutter_rounded_date_picker: ^2.0.2
  date_format: ^2.0.2
  pin_code_fields: ^7.3.0
  keyboard_dismisser: ^2.0.0
  sticky_headers: ^0.2.0
  #Library helpful
  intl: ^0.17.0
  event_bus: ^2.0.0
  equatable: ^2.0.0
  fluttertoast: 8.0.3
  retrofit: ^2.0.1
  json_annotation: ^4.0.1
  flutter_screenutil: 5.0.0
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  syncfusion_flutter_datepicker: ^19.4.55
  logger: any
  rxdart: ^0.27.1
  hive: ^2.0.5
  just_audio: ^0.9.20
  speech_to_text: 5.4.3
  flutter_tts: ^3.3.3
  local_auth: ^1.1.11
  dropdown_button2: 1.2.0
  file_picker: ^4.0.2
  cool_alert: ^1.1.0
  expandable: 5.0.1
  queue: ^3.1.0+1
  readmore: any
  flutter_countdown_timer: ^4.1.0

  dots_indicator: ^2.0.0
  dotted_border:
  #svg
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.0

  # GET
  get: ^4.1.4
  pretty_dio_logger: ^1.1.1

  injectable: ^1.4.1
  freezed: ^0.14.2
  tuple: ^2.0.0
  html_editor_enhanced: ^2.4.0+1
  flutter_contacts:
  audioplayers: ^0.20.1
  lunar_calendar_converter_new: ^2.0.0
  carousel_slider: ^4.1.1

  #firebase
  firebase_messaging_platform_interface: 3.1.6
  firebase_messaging: 11.2.0
  firebase_core: ^1.12.0
  http: ^0.13.4
  platform_device_id: ^1.0.1
  sound_mode: ^2.0.2
  transparent_pointer: ^1.0.0
  #lazy load more
  grouped_list: ^5.1.2
  expandable_page_view: ^1.0.13
  analyzer: ^1.7.2
  dropdown_search: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  hive_generator:
  build_runner: 2.1.1  #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.0
  injectable_generator: ^1.4.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/home_module/assets/images/
    - lib/tien_ich_module/assets/images/
    - assets/images/
    - assets/menu/
    - assets/style/
    - lib/ket_noi_module/assets/images/
    - lib/nhiem_vu_module/assets/images/
    - lib/diem_danh_module/assets/images/
    - lib/bao_cao_module/assets/images/
    - lib/ho_tro_ky_thuat_module/assets/images/
flutter_intl:
  enabled: true
